apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
spec:
  serviceName: atlantis
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: atlantis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atlantis
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: atlantis
          image: ghcr.io/runatlantis/atlantis:v0.36.0
          env:
            - name: ATLANTIS_REPO_ALLOWLIST
              value: github.com/ThomasCardin/homelab

            ### GitHub Config ###
            - name: ATLANTIS_GH_USER
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: user
            - name: ATLANTIS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: token
            - name: ATLANTIS_GH_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: webhook-secret
            ### End GitHub Config ###

            ### Terraform cloud config ###
            - name: ATLANTIS_TFE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: tf_token
            ### End of Terraform cloud config ###

            - name: ATLANTIS_DATA_DIR
              value: /atlantis
            - name: ATLANTIS_PORT
              value: "4141" # Kubernetes sets an ATLANTIS_PORT variable so we need to override.
          volumeMounts:
            - name: atlantis-data
              mountPath: /atlantis
          ports:
            - name: atlantis
              containerPort: 4141
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 4141
              scheme: HTTP
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 4141
            scheme: HTTP
  volumeClaimTemplates:
    - metadata:
        name: atlantis-data
      spec:
        storageClassName: hdd-ceph-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: atlantis
spec:
  type: ClusterIP
  ports:
  - name: atlantis
    port: 80
    targetPort: 4141
  selector:
    app.kubernetes.io/name: atlantis