---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgCveqvVADUDDpbHyxK0zvRqliSAJmm+eko59r/vgD/apCl0mh/02/PnfPeWUeRgnQUiCZe+FJKWbb4dGX3KW+zli+6FOh0uXPFItkxxEK8KJ5LJ3R2Aj9i8OD73Wsb7AOh9gSk4RuZLKRMkI2Ds0kR1w2yyKVBWSHHF0wgE2v1an06qWEF7qHdbQ8BlnNHDFwWi1eSCmGIJV8VzTh3y8PMAnLZ0zbvjSgSdGctfIb5jXvjtXmEGvjYExky25KipRAEXd0QkIi+1yLcLp8fZzaa/hD5rfw7sU6ed0MdAmsF2UV6xnz82scPMbkd8LH/l7A7fioTZtqFHvJ4TZn8ncmJm+e6l2frod34FT64PT+BYvn2lvk31FcGwM2MDhVRwRpMeRNhUBC225Bw4yEtyobORX6ukvz8Rjlqo7DZQerxGcadWNoYyiHQ8be/me2r7ZuF/ca7tQZU0vHUD0x7ANMv3JhbBUcY5b0k5FqnLCVsWfQi0ipEP6gqVQsjw44fhasH6n633GZZYEIW9a3QfsZ57a37GGZNMtOjxPUHrsBXzTTH5tnE+0v82mR/ENNVxZL51q6YZ1RXDFJR7gAZpim9ekdckBgDVD3deXW9VEbQHq5+qiKiuKbGzp1bV67NCaG3iI+apbasDgwDAG6Kxd+gVwnhCo13/iu1uiIdNRTaoLkNwrGQkKfS7DN0ywXEdjICG65hkbqGBrBtke58t3GsRqaeJ
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgres-user
      namespace: immich
    type: Opaque
