apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-deployment
  namespace: ddns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ddns
  template:
    metadata:
      labels:
        app: ddns
    spec:
      containers:
      - name: ddns
        image: ghcr.io/thomascardin/ddns:1.0.0
        env:
          - name: NOIP_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: ddns-secrets
                key: NOIP_HOSTNAME 
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: ddns-secrets
                key: CLOUDFLARE_EMAIL 
          - name: CLOUDFLARE_API_KEY
            valueFrom:
              secretKeyRef:
                name: ddns-secrets
                key: CLOUDFLARE_API_KEY 
          - name: CLOUDFLARE_A_RECORD_NAME
            valueFrom:
              secretKeyRef:
                name: ddns-secrets
                key: CLOUDFLARE_A_RECORD_NAME 
          - name: CLOUDFLARE_ZONE_ID
            valueFrom:
              secretKeyRef:
                name: ddns-secrets
                key: CLOUDFLARE_ZONE_ID 
          
