apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    - chart: cilium
      helm:
        releaseName: cilium
        valueFiles:
        - $values/kubernetes/system/cilium/helm/values.yaml
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.15.1
    - repoURL: 'https://github.com/ThomasCardin/homelab'
      targetRevision: master
      ref: values
    - repoURL: 'https://github.com/ThomasCardin/homelab'
      path: kubernetes/system/cilium/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
