apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - chart: cilium
      helm:
        releaseName: cilium
        valueFiles:
        - $values/kubernetes/system/cilium/helm/values.yaml
      repoURL: https://helm.cilium.io/
      targetRevision: 1.15.6
    - repoURL: https://github.com/ThomasCardin/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ThomasCardin/homelab
      path: kubernetes/system/cilium/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
