apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  sources:
    - chart: ingress-nginx
      helm:
        releaseName: ingress-nginx
        valueFiles:
        - $values/kubernetes/system/ingress-nginx/helm/values.yaml
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.10.1
    - repoURL: https://github.com/ThomasCardin/homelab
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
