apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-db-pvc
  namespace: htpc
spec:
  storageClassName: hdd-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode-pvc
  namespace: htpc
spec:
  storageClassName: hdd-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-pvc
  namespace: htpc
spec:
  storageClassName: hdd-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi