apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-key: Y2UyMjc3OTA5YTU5MTdiYzk2NTVmYmUxYjg0MTgwZWZlZGNlYg==

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tomcardin@outlook.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: tomcardin@outlook.com
          apiKeySecretRef:
            name: cloudflare-api-token
            key: api-key
