apiVersion: batch/v1
kind: CronJob
metadata:
  name: jobscrapper-cronjob
spec:
  schedule: "0 7 * * *" # Run every day at 7:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: jobscrapper
              image: ghcr.io/thomascardin/jobscrapper:v1.0.3
              env:
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: jobscrapper-secrets
                      key: DISCORD_WEBHOOK_URL 
                - name: JOBS_SCRAPPER_LIST
                  value: "golang,sre,devops,cloud"
                - name: JOBS_SCRAPPER_LOCATION
                  value: "Montreal, QC, CA"
                - name: JOBS_SCRAPPER_COUNTRY
                  value: "Canada"
          restartPolicy: OnFailure
