apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gobservability-postgres
  namespace: gobservability
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  instances: 1

  postgresql:
    parameters:
      timezone: "America/Montreal"

  managed:
    roles:
      - name: gobs
        login: true
        createdb: true

  bootstrap:
    initdb:
      database: gobservability
      owner: gobs
      secret:
        name: postgres-user-secret
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  storage:
    size: 20Gi
    storageClass: hdd-ceph-block