apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    - chart: kubeshark
      helm:
        releaseName: kubeshark
        valueFiles:
          - $values/kubernetes/system/monitoring/helm/kubeshark.values.yaml
      repoURL: https://helm.kubeshark.co
      targetRevision: 52.3.0
    - repoURL: https://github.com/ThomasCardin/homelab.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true