apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    - chart: kube-prometheus-stack
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/kubernetes/system/monitoring/helm/kube-prometheus-stack.values.yaml
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 56.13.1
    - repoURL: https://github.com/ThomasCardin/homelab.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true