apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  sources:
    - chart: sealed-secrets
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/kubernetes/system/sealed-secrets/helm/values.yaml
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.16.2
    - repoURL: https://github.com/ThomasCardin/homelab.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
