---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: odoo
spec:
  encryptedData:
    postgres-password: AgCYwvuSBuEolMPcROaYUOqongdIWhHxlAqeU0gh00wpeL27pR0xSmVk5HV7hnJIPaPSu/Tv0m8p8e/wCSN7WbN9t5qP+NHUq7B8dyYMotc1/vriL/uVsyjHo7vNXJXnZPJnOseCcS+DBBlfmXv9hYEccJOndMUJPPM4SiWcWFyZRVSKiquKnKoPGJAY9fSFeuehsdw+dsgSaKpKa4ZXe9IN9xPC51tMGwfI4zbiMyCEEDPVn6Wjmc1HT5yZtizYxoYSA1jcd0tO8H4oH/XKMYjiE6MLls48zF8qyR277NUwKnVWv8vs67USTwzAd/vu6LOpQrS/gcyAhwjYq2DdhOwWkj8+eJ2GoW2QfZOloE0LTfhFatTlEmvX8qjv7J/OGgftfxmNn2Nyd0yJNNvTBlqVz5lyK4XHXR4iIy0uJAoYWFk7O80bdb3j6rZ/xwzHr+kbsFr8bQOUn01pptJa8UKiZXn6vYfgSuNTAU8iS0qYi9KNQPdJwB12RFlYms9s6oMTCivvKrvmnHaHWnAESP4Yp4M4hNDi2pEM4Q+ZSpUYtLMsNuN45qdSqeGEuiWkng2iiYHQJVwnPost3/ATinVow5wfGE8w0IeHVJjHdARCOtsn8gzYx06on31rsWUTJTvIYGbjwcP3A4PrR7b8pz2yi9bpi7sw0sYnNL2w53VJhZGgNksAhiKLGZ1yMhQAwDiUE1VGzzI3YOc6Q2wj
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: odoo
    type: Opaque