apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - cluster/cluster.yaml
 - cluster/rook-ceph-default-sa.yaml
 - blocks/hdd-ceph-block.yaml
 - httproutes.yaml
 - cephfs/hdd-ceph-cephfs.yaml