apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    GITHUB_CLIENT_SECRET: AgBteNRDLK16HA51aeC/k9rztydI+l455hVGmgajtGcIVQ2AFAWqOqF7A2pVVFGfUrZ8YSbkSHb9oXL/diEWEHWN5fmOtlzzQJu1q6jh7XUqUorw5Z9Rwr2AtgqG4FSEhvgJKiHuhb1qfO1S8zpL0xkPtXBFkZIfvqOOVGUPa7dPYco9QPKJqr0sN5GB/MSVaPKnY1ZP6tuL6u/9Cb77hla6XoCXLm4cCPmoBtyVJLgUd4kYsgEL+fuPJvSSVecb0s8k24hgtrsQGS+pDUYfg0E8BklcHw/Krm7Ag6/QMdfd8Wg08hkm/pW6obWExuaEsGctHHyOa12fpQk25/todf1AjlghkLLDAX2k06qBKbF1RlNeyiUWqbctdLXo3csxNYAoUOCVO49SJHvV/mXWolJm5uKwka8jGE1gyphjnQrd54FLsPsxSx4hYwV4pd5uDnyssP37pgN/SXWjX4FK5l6FRa3s9l1G0+GgEnxUijIscdG1FzbYE2Q/49EAVJpV/RdstkxdI7kCki1aUg2JVssOvCrO2kKCxxcGwKd73xzaeSV5ErQkWRtqHBM+WsoyhuWvlljr6NfsoOFyR5HPmoh8bbH5GubJzCQJN0F9TUDoylaOA1xRkl6982wnaLo5leih0ifv9TD1qo+TxAsLIvRFSNgFs8ThQ0y2H3BJjbgKecZK6JL0hdmV8iu6930tQ5900OVKOHnQgLqkCoOlSW8lqowvdv0sNHh75VKuBxngRQEgSQYtfGOE
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring

