apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx
data:
  nginx.conf: |
    server {
      listen 80;
      server_name nginx.ninebasetwo.net;

      location / {
        root /usr/share/nginx/html;
      }
    }

    server {
      listen 443 ssl;
      server_name nginx.ninebasetwo.net;

      ssl_certificate /etc/ssl/certs/ca-certificates.crt;
      ssl_certificate_key /etc/ssl/certs/ca-certificates.key;

      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256;

      location / {
        root /usr/share/nginx/html;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: nginx-tls-volume
          mountPath: "/etc/ssl/certs"
        - name: nginx-conf
          mountPath: "/etc/nginx/conf.d"
      volumes:
      - name: nginx-tls-volume
        secret:
          secretName: nginx-tls
          defaultMode: 440
      - name: nginx-conf
        configMap:
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-external-nginx
  namespace: nginx
spec:
  parentRefs:
  - name: external-gateway
    namespace: networking
  hostnames:
    - "nginx.ninebasetwo.net"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nginx
      port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-nginx-internal
  namespace: nginx
spec:
  parentRefs:
  - name: internal-gateway
    namespace: networking
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nginx
      port: 80

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress
#   namespace: nginx
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   ingressClassName: cilium
#   tls:
#     - hosts:
#         - privatebin.ninebasetwo.net
#       secretName: privatebin-tls
#   rules:
#     - host: privatebin.ninebasetwo.net
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: nginx
#                 port:
#                   number: 80