apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    name: nginx
    pod-security.kubernetes.io/enforce: privileged

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service 
metadata:
  name: nginx
  namespace: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo-gateway
  namespace: nginx
  labels:
    app: cilium-gateway-demo-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  listeners:
  # Test locally with the external port and control-plane IP adresse
  # Or modify the /etc/hosts and set the nginx.ninebasetwo.net to the LB IP
  # - name: nginx-http
  #   port: 80
  #   protocol: HTTP
  #   allowedRoutes:
  #     namespaces:
  #       from: Same
  - name: nginx-https
    hostname: "*.ninebasetwo.net"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls: 
      mode: Terminate 
      certificateRefs:
        - name: demo-gateway-tls 
          kind: Secret  
          group: core 
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-nginx-1
  namespace: nginx
spec:
  parentRefs:
  - name: demo-gateway
    namespace: nginx
  hostnames:
    - "nginx.ninebasetwo.net"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nginx
      port: 80