apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: odoo
  sources:
    - chart: odoo
      helm:
        releaseName: odoo
        valueFiles:
          - $values/kubernetes/apps/odoo/helm/values.yaml
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 28.2.10
    - repoURL: https://github.com/ThomasCardin/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ThomasCardin/homelab.git
      path: kubernetes/apps/odoo/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true