apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio-config
  namespace: factorio
data:
  map-gen-settings.json: |
    {
      "seed": 987654321
    }
  server-settings.json: |
    {
      "name": "Factorio Server",
      "description": "A Factorio server running on Kubernetes",
      "tags": ["kubernetes", "homelab"],
      "max_players": 20,
      "visibility": {
        "public": false,
        "lan": true
      },
      "require_user_verification": false,
      "max_upload_in_kilobytes_per_second": 0,
      "max_upload_slots": 5,
      "minimum_latency_in_ticks": 0,
      "max_heartbeats_per_second": 60,
      "ignore_player_limit_for_returning_players": false,
      "allow_commands": "admins-only",
      "autosave_interval": 10,
      "autosave_slots": 5,
      "afk_autokick_interval": 0,
      "auto_pause": true,
      "only_admins_can_pause_the_game": true,
      "autosave_only_on_server": true,
      "non_blocking_saving": false,
      "minimum_segment_size": 25,
      "minimum_segment_size_peer_count": 20,
      "maximum_segment_size": 100,
      "maximum_segment_size_peer_count": 10
    }
