apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-data
  namespace: factorio
spec:
  storageClassName: hdd-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
