apiVersion: v1
kind: Service
metadata:
  name: factorio-svc
  namespace: factorio
spec:
  type: NodePort
  selector:
    app: factorio
  ports:
    - name: game
      protocol: UDP
      port: 34197
      targetPort: 34197
      nodePort: 30197
    - name: rcon
      protocol: TCP
      port: 27015
      targetPort: 27015
      nodePort: 30015
