apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cluster-pool"
spec:
  cidrs:
    - cidr: 192.168.2.0/24
  blocks:
    - start: "192.168.2.100"
      stop: "192.168.2.130"