apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: htpc
    server: https://kubernetes.default.svc
  sources:
    - chart: plex
      helm:
        releaseName: plex
        valueFiles:
          - $values/kubernetes/apps/plex/helm/values.yaml
      repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
      targetRevision: 6.4.0
    - repoURL: https://github.com/ThomasCardin/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ThomasCardin/homelab.git
      path: kubernetes/apps/plex/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true