existingSecret: "litmus-admin-secret"

adminConfig:
  ADMIN_USERNAME: ""  # From existingSecret
  ADMIN_PASSWORD: ""  # From existingSecret
  DB_SERVER: "mongodb-service.litmus.svc.cluster.local"
  DB_PORT: "27017"
  DB_USER: ""  # From existingSecret
  DB_PASSWORD: ""  # From existingSecret

ingress:
  enabled: true
  name: litmus-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  ingressClassName: nginx
  host:
    name: litmus.ninebasetwo.net
    frontend:
      path: /
      pathType: Prefix
  tls:
    - secretName: litmus-tls
      hosts:
        - litmus.ninebasetwo.net

# see base/mongodb-deployment.yaml
mongodb:
  enabled: false

portal:
  frontend:
    replicas: 1
    resources:
      requests:
        memory: "150Mi"
        cpu: "125m"
      limits:
        memory: "512Mi"
        cpu: "550m"
  server:
    replicas: 1
    graphqlServer:
      resources:
        requests:
          memory: "250Mi"
          cpu: "225m"
        limits:
          memory: "712Mi"
          cpu: "550m"
    authServer:
      replicas: 1
      resources:
        requests:
          memory: "250Mi"
          cpu: "225m"
        limits:
          memory: "712Mi"
          cpu: "550m"