# Configuration des secrets
existingSecret: "litmus-secrets"

# Configuration pour ARM64 - utilise une image MongoDB compatible
mongodb:
  image:
    registry: ghcr.io/zcube
    repository: bitnami-compat/mongodb
    tag: "6.0.5"
  auth:
    enabled: true
    existingSecret: "litmus-secrets"
  architecture: replicaset
  replicaCount: 1
  persistence:
    enabled: true
    size: 20Gi
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
      tag: 12-debian-12-r47
  metrics:
    enabled: false

# Configuration des services pour NodePort (comme dans la doc)
portal:
  frontend:
    service:
      type: NodePort
    replicas: 1
    resources:
      requests:
        memory: "150Mi"
        cpu: "125m"
      limits:
        memory: "512Mi"
        cpu: "550m"
  server:
    replicas: 1
    graphqlServer:
      resources:
        requests:
          memory: "250Mi"
          cpu: "225m"
        limits:
          memory: "712Mi"
          cpu: "550m"
      genericEnv:
        CHAOS_CENTER_UI_ENDPOINT: "https://litmus.ninebasetwo.net"
    authServer:
      replicas: 1
      resources:
        requests:
          memory: "250Mi"
          cpu: "225m"
        limits:
          memory: "712Mi"
          cpu: "550m"

# Configuration Ingress avec cert-manager
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  ingressClassName: nginx
  host:
    name: litmus.ninebasetwo.net
    frontend:
      path: /
      pathType: Prefix
  tls:
    - secretName: litmus-tls
      hosts:
        - litmus.ninebasetwo.net