# Configuration pour le chart Bitnami Odoo
# https://artifacthub.io/packages/helm/bitnami/odoo

# Configuration de base avec secrets
existingSecret: odoo-credentials
allowEmptyPassword: true

# Configuration des credentials via secrets existants
odooEmail: admin@ninebasetwo.net

# Configuration PostgreSQL externe (CloudNativePG)
postgresql:
  enabled: false  # Désactiver PostgreSQL intégré

externalDatabase:
  host: odoo-postgres-rw.odoo.svc.cluster.local
  port: 5432
  user: odoo
  database: odoo
  existingSecret: odoo-postgres-user
  existingSecretPasswordKey: password

# Configuration du stockage
persistence:
  enabled: true
  size: 10Gi
  storageClass: hdd-ceph-block
  accessModes:
    - ReadWriteOnce

# Configuration Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: odoo.ninebasetwo.net
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls: true

# Configuration des ressources
resources:
  requests:
    memory: 512Mi
    cpu: 300m
  limits:
    memory: 2Gi
    cpu: 1000m

# Configuration du service
service:
  type: ClusterIP
  ports:
    http: 8069

# Configuration de sécurité
podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true

# Volume permissions
volumePermissions:
  enabled: true