# Configuration simple pour Odoo avec PostgreSQL intégré

# Configuration Odoo avec secrets
odooEmail: admin@ninebasetwo.net
existingSecret: odoo-credentials

# PostgreSQL intégré avec secret
postgresql:
  enabled: true
  auth:
    username: odoo
    database: odoo
    existingSecret: postgresql-secret
    secretKeys:
      adminPasswordKey: postgres-password

# Stockage
persistence:
  enabled: true
  size: 10Gi
  storageClass: hdd-ceph-block

# Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: odoo.ninebasetwo.net
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: true

# Ressources
resources:
  requests:
    memory: 512Mi
    cpu: 300m
  limits:
    memory: 2Gi
    cpu: 1000m