apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: litmus
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        command:
          - sh
          - -c
          - |
            exec mongod --replSet rs0 --bind_ip_all &
            MONGO_PID=$!
            
            # Wait for MongoDB to start
            until mongosh --eval "print('MongoDB is ready')" > /dev/null 2>&1; do
              sleep 2
            done
            
            # Initialize replica set
            mongosh --eval "
            try {
              rs.status();
              print('Replica set already initialized');
            } catch (e) {
              print('Initializing replica set...');
              rs.initiate({
                _id: 'rs0',
                members: [{ _id: 0, host: 'localhost:27017' }]
              });
              print('Replica set initialized');
            }
            "
            
            # Wait for the MongoDB process
            wait $MONGO_PID
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: litmus-admin-secret
              key: DB_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: litmus-admin-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: litmus
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb