apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habitica
  template:
    metadata:
      labels:
        app: habitica
    spec:
      containers:
      - name: mongo
        image: mongo:3.6
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        
      - name: habitica-server
        image: ghcr.io/thomascardin/habitica:5.24.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_DB_URI
          value: "mongodb://habitica-mongo:27017/habitrpg"
        command: ["/bin/sh", "-c"]
        args: ["npm start"]

      - name: habitica-client
        image: ghcr.io/thomascardin/habitica:5.24.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: BASE_URL
          value: "http://habtica-server:3000"
        command: ["/bin/sh", "-c"]
        args: ["npm run client:dev"]

      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
