apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habitica
  template:
    metadata:
      labels:
        app: habitica
    spec:
      containers:        
      - name: habitica-server
        image: ghcr.io/thomascardin/habitica:5.24.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_DB_URI
          value: "mongodb://mongodb:27017/habitrpg"
        - name: NODE_ENV
          value: "development"
        command: ["/bin/sh", "-c"]
        args: ["node ./website/server/index.js"]

      - name: habitica-client
        image: ghcr.io/thomascardin/habitica:5.24.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: BASE_URL
          value: "http://habitica-server:3000"
        - name: NODE_ENV
          value: "development"
        command: ["/bin/sh", "-c"]
        args: ["npm run client:dev"]

---
apiVersion: v1
kind: Service
metadata:
  name: habitica-server
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: habitica

---
apiVersion: v1
kind: Service
metadata:
  name: habitica-client
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: habitica
  type: ClusterIP
