apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  sources:
    - chart: external-dns
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/kubernetes/system/external-dns/helm/values.yaml
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.14.5
    - repoURL: https://github.com/ThomasCardin/homelab.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
